Description: >
  Supplementary resources for squid-cluster
Parameters:
  BufferInterval:
    Type: Number
    Default: 180
    Description: Firehose buffer interval in seconds, default 180
  BufferSize:
    Type: Number
    Default: 5
    Description: Firehose buffer size in mb, default 5
  LogPrefix:
    Type: String
Resources:
  ConfigBucket:
    Type: AWS::S3::Bucket
  LogBucket:
    Type: AWS::S3::Bucket
  FirehoseDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      S3DestinationConfiguration:
        BucketARN: !GetAtt LogBucket.Arn
        BufferingHints:
          IntervalInSeconds: !Ref BufferInterval
          SizeInMBs: !Ref BufferSize
        CompressionFormat: GZIP
        Prefix: !Ref LogPrefix
        RoleARN: !GetAtt FirehoseServiceRole.Arn
  FirehoseServiceRole:
    Type: AWS::IAM::Role
    Properties:
        AssumeRolePolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Principal:
                  Service: firehose.amazonaws.com
                Action: sts:AssumeRole
                Condition:
                  StringEquals: {"sts:ExternalId": !Ref "AWS::AccountId"}
        Policies:
          - PolicyName: write-to-log-bucket
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - s3:AbortMultipartUpload
                    - s3:GetBucketLocation
                    - s3:GetObject
                    - s3:ListBucket
                    - s3:ListBucketMultipartUploads
                    - s3:PutObject
                  Resource:
                    - !GetAtt LogBucket.Arn
                    - !Join ["", [ !GetAtt LogBucket.Arn, "/*"]]
  SquidClusterInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref SquidClusterRole
  SquidClusterRole:
    Type: AWS::IAM::Role
    Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - ec2.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: read-from-config-bucket
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action: s3:GetObject
                  Resource: !Join ["", [ !GetAtt ConfigBucket.Arn, "/*"]]
          - PolicyName: write-to-kinesis-firehose
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - firehose:PutRecord
                    - firehose:PutRecordBatch
                  Resource:
                    Fn::Join:
                      - ""
                      - - "arn:aws:firehose:"
                        - !Ref AWS::Region
                        - ":"
                        - !Ref AWS::AccountId
                        - ":deliverystream/"
                        - !Ref FirehoseDeliveryStream
Outputs:
  SquidClusterInstanceProfileArn:
    Value: !GetAtt SquidClusterInstanceProfile.Arn
  LogBucketName:
    Value: !Ref LogBucket
  ConfigBucketName:
    Value: !Ref ConfigBucket
